version: "3.8"
services:
  backend:
    image: "gebeyer/springboot-react-fullstack:19.11.2022.22.8.22"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
