version: "3.8"
services:
  backend:
    image: "gebeyer/springboot-react-fullstack:15.11.2022.4.39.54"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
