version: "3.8"
services:
  backend:
    image: "gebeyer/springboot-react-fullstack:14.11.2022.20.40.40"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
