version: "3.8"
services:
  backend:
    image: "gebeyer/springboot-react-fullstack:21.11.2022.23.23.41"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
